FROM node:20-alpine

RUN apk add --no-cache python3 make g++ 
WORKDIR /app
COPY package*.json ./
RUN npm install
...

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file: ./server/.env

  admin:
    build: ./admin
    ports:
      - "5173:80"

  client:
    build: ./client
    ports:
      - "5174:80"
