
services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file: ./server/.env

  admin:
    build: ./admin
    ports:
      - "5173:80"

  client:
    build: ./client
    ports:
      - "5174:80"
