name: Docker Deploy LabMate

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # If the directory doesn't exist, clone it; otherwise, just enter it
            if [ ! -d "~/LabMate" ]; then
              git clone https://github.com/sushantrajput/LabMate.git ~/LabMate
            fi
            
            cd ~/LabMate
            
            # Pull latest changes
            git pull origin main
            
            # Docker commands
            # Using 'sudo' if you haven't finished the 'usermod' step yet
            docker compose down
            docker system prune -f
            docker compose up --build -d